name: Deploy CappsDapr to Azure Container Apps
concurrency: capps-dapr

on:    
  push:
    branches:
      - deploy
    paths:
      - 'components/**'
      - 'deploy/**'
      - 'src/**'
      - '.github/workflows/**'

env:
    # Specify your resource group's name
    RESOURCE_GROUP_NAME: cappsdapr

    # Specify your preferred region
    LOCATION: westeurope

    BACKEND_DOCKER: MyBackEnd/Dockerfile
    BACKEND_IMAGE: backend

    FRONTEND_DOCKER: MyFrontEnd/Dockerfile
    FRONTEND_IMAGE: frontend

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout to the branch
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SPN }}

    - name: Installing Container Apps extension
      uses: azure/CLI@v1
      with:
        inlineScript: >
          az config set extension.use_dynamic_install=yes_without_prompt
          az extension add -n containerapp